name: Clang Format Check

on:
  push:
    branches:
      - main  # Adjust branch name as needed
  pull_request:
    branches:
      - main  # Adjust branch name as needed

jobs:
  clang-format-check:
    runs-on: ubuntu-latest  # Choose an appropriate runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      name: Install Clang Format

on:
  push:
    branches:
      - main

jobs:
  install-clang-format:
    runs-on: ubuntu-latest

    steps:
      - name: Download Clang and LLVM Source Code
        run: wget https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.2/clang+llvm-18.1.2.src.tar.xz

      - name: Extract Clang and LLVM Source Code
        run: tar -xf clang+llvm-18.1.2.src.tar.xz

      - name: Build Clang Format
        run: |
          cd clang+llvm-18.1.2.src
          mkdir build
          cd build
          cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ..
          cmake --build .

      - name: Install Clang Format Binary
        run: sudo cp bin/clang-format /usr/local/bin/

      - name: Verify Clang Format Installation
        run: clang-format --version


      - name: Check code formatting with Clang Format
        id: clang-format-check
        run: |
          if clang-format --style file --dry-run --Werror src/*.cpp src/*.h; then
            echo "Code formatting check passed."
          else
            echo "Code formatting check failed."
            exit 1
          fi
