name: Clang Format Check

on:
  push:
    branches:
      - main  # Adjust branch name as needed
  pull_request:
    branches:
      - main  # Adjust branch name as needed

jobs:
  clang-format-check:
    runs-on: ubuntu-latest  # Choose an appropriate runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download Clang Format
        run: wget https://github.com/llvm/llvm-project/releases/download/llvmorg-14.0.0/clang+llvm-14.0.0-x86_64-linux-gnu-ubuntu-20.04.tar.xz

      - name: Extract Clang Format
        run: tar -xvf clang+llvm-14.0.0-x86_64-linux-gnu-ubuntu-20.04.tar.xz

      - name: Move Clang Format Binary
        run: sudo mv clang+llvm-14.0.0-x86_64-linux-gnu-ubuntu-20.04/bin/clang-format /usr/local/bin/

      - name: Verify Clang Format Installation
        run: clang-format --version

      - name: Check code formatting with Clang Format
        id: clang-format-check
        run: |
          if clang-format --style file --dry-run --Werror src/*.cpp src/*.h; then
            echo "Code formatting check passed."
          else
            echo "Code formatting check failed."
            exit 1
          fi
