name: Clang Format Check

on:
  push:
    branches:
      - main  # Adjust branch name as needed
  pull_request:
    branches:
      - main  # Adjust branch name as needed

jobs:
  clang-format-check:
    runs-on: ubuntu-latest  # Choose an appropriate runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download clangFormat
        run: |
          sudo apt update
          sudo apt install -y clang-format 

      - name: Verify Clang Format Installation
        run: clang-format --version


      - name: Check code formatting with Clang Format
        id: clang-format-check
        run: |
          if ! output=$(clang-format --style=file --dry-run --Werror src/*.cpp src/*.h 2>&1); then
            echo "::error::Code formatting check failed."
            echo "$output"
            exit 1
          else
            echo "Code formatting check failed."
            exit 1
          fi
